server:
    port: 9001


#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://server7001:7001/eureka/,http://server7002:7002/eureka/,http://server7003:7003/eureka/
  instance:
    instance-id: microserviceconsumer9001
    prefer-ip-address: true




spring:
  application:
    name: microservice-consumer
  zipkin:
    base-url: http://localhost:9411  # zipkin server地址和端口
    sender:
      type: web  #zipkin消息传送发送方式，采用Http协议
  sleuth:
    sampler:
      probability: 1 # sleuth配置采样比，默认是0.1

#解决eureka控制台中的Info页面错误问题
info:
  app.name: com.xyz.microservice
  build.artifactId: $project.artifactId$ #使用maven内置变量project.artifactId和project.version完成对变量的赋值
  build.version: $project.version$

# 修改ribbon默认算法 spring.application.name + ribbon.NFLoadBalancerRuleClassName
microservice-consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    HystrixCommandKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#暴露hystrix dashboard的全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]

