server:
  port: 8001

spring:
  application:
    name: microservice-provider   #微服务名称
  zipkin:
    base-url: http://localhost:8500  # zipkin server地址和端口
    sender:
      type: web  #消息传送发送方式，采用Http协议
  sleuth:
    sampler:
      probability: 1 # 配置采样比，默认是0.1



#eureka注册信息
eureka:
  client:
    service-url:  #注册中心地址列表
#      defaultZone: http://localhost:7001/eureka/  #单机注册地址
      defaultZone: http://server7001:7001/eureka/,http://server7002:7002/eureka/,http://server7003:7003/eureka/
  instance:
    instance-id: micoroserviceprovider8001  # 自定义控制台中微服务名称
    prefer-ip-address: true  #eureka控制访问路径显示ip

#解决eureka控制台中的Info页面错误问题
info:
  app.name: com.xyz.microservice
  build.artifactId: $project.artifactId$ #使用maven内置变量project.artifactId和project.version完成对变量的赋值
  build.version: $project.version$