server:
  port: 8501

spring:
  application:
    name: streamconsumer-8501
  rabbitmq:  #rabbiqmq连接信息
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    stream:
      bindings:  #stream channel
        input:
          destination: test-producer #消息接收队列名称
        myinput:
          destination: costom-topic #消息接收队列名称
          group: mygroup #设置消费者组
      binders:  #绑定器
        defaultRabbit:
          type: rabbit
