server:
    port: 9101


eureka:
  client:
    service-url:
      defaultZone: http://server7001:7001/eureka/,http://server7002:7002/eureka/,http://server7003:7003/eureka/
  instance:
    instance-id: microserviceconsumerfeign9101
    prefer-ip-address: true


#在Feign中开发Hystrix
feign:
  hystrix:
    enabled: true

spring:
  application:
    name: microservice-consumerfeign

#解决eureka控制台中的Info页面错误问题
info:
  app.name: com.xyz.microservice
  build.artifactId: $project.artifactId$ #使用maven内置变量project.artifactId和project.version完成对变量的赋值
  build.version: $project.version$

#暴露hystrix dashboard的全部监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"