server:
  port: 6001

eureka:
  instance:
    instance-id: Zuul-6001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://server7001:7001/eureka/,http://server7002:7002/eureka/,http://server7003:7003/eureka/


  #解决eureka控制台中的Info页面错误问题
info:
  app.name: com.xyz.microservice
  build.artifactId: $project.artifactId$ #使用maven内置变量project.artifactId和project.version完成对变量的赋值
  build.version: $project.version$

spring:
  application:
    name: microservicezuul
zuul:
  routes:
    mydept.serviceId: microservice-provider  #原服务名称
    mydept.path: /mydept/**   #映射后的路径
  ignored-services: "*" #禁止所有的服务通过原路径访问
  #  ignored-services: microservice-provider #禁止通过原路径访问
  prefix: /xyz #增加统一的访问前缀
