spring:
  application:
    name: microservice-turbine

server:
  port: 8201

turbine:
  aggregator:
    cluster-config: default # 指定聚合那些集群，多个使用“,"分隔，模式default
  app-config: microservice-consumer,microservice-consumerfeign  #配置eureka中的serviceID列表，标明监控那些服务
  cluster-name-expression: new String("default")

eureka:
  client:
    service-url:
      defaultZone: http://server7001:7001/eureka/,http://server7002:7002/eureka/,http://server7003:7003/eureka/
  instance:
    instance-id: MicroServiceTurbine
    prefer-ip-address: true

#解决eureka控制台中的Info页面错误问题
info:
  app.name: com.xyz.microservice
  build.artifactId: $project.artifactId$ #使用maven内置变量project.artifactId和project.version完成对变量的赋值
  build.version: $project.version$
