server:
  port: 8502

spring:
  application:
    name: streamconsumer-8502
  rabbitmq:  #rabbiqmq连接信息
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    stream:
      bindings:  #stream channel
        input:
          destination: test-producer #消息接收队列名称
        myinput:
          destination: costom-topic #消息接收队列名称
          group: mygroup #设置消费者组
          consumer:
            partitioned: true #消费者端开启对分区的支持
      binders:  #绑定器
        defaultRabbit:
          type: rabbit
      instanceIndex: 1
      instanceCount: 2
