server:
  port: 8500

spring:
  application:
    name: streamproduder-8500
  rabbitmq:  #rabbiqmq连接信息
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    stream:
      bindings:  #stream channel
        output:
          destination: test-producer #消息发送的目的地，在rabbitmq中指的是exchange
      binders:  #绑定器
        defaultRabbit:
          type: rabbit
